CREATE TABLE `order0` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order1` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order2` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order3` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order4` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order5` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order6` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order7` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order8` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order9` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order10` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order11` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order12` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order13` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order14` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
CREATE TABLE `order15` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
  `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID',
  `order_number` varchar(50) NOT NULL COMMENT '订单号',
  `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '原总金额',
  `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总金额',
  `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
  `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 1 微信支付 2 支付宝 3.银行卡 4其他',
  `remarks` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:取消',
  `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
  `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式，物流配送',
  `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
  `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
  `order_addr_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
  `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
  `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
  `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
  `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已支付，0：未支付',
  `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：未删除， 1：回收站， 2：永久删除',
  `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
  `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
  `create_at` datetime DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `last_update_at` datetime DEFAULT NULL,
  `last_update_by` varchar(50) DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_number_unique_ind` (`order_number`)
) ENGINE=InnoDB AUTO_INCREMENT=5010001 DEFAULT CHARSET=utf8mb4 COMMENT='订单表';


